package config

const (
	//下面5个参数要从环境变量中读取
	SERVER_PORT               = "SERVER_PORT"
	ORDER_MYSQL_DATABASE_NAME = "ORDER_MYSQL_DATABASE_NAME"
	ORDER_MYSQL_HOST          = "ORDER_MYSQL_HOST"
	ORDER_MYSQL_USER          = "ORDER_MYSQL_USER"
	ORDER_MYSQL_PASSWORD      = "ORDER_MYSQL_PASSWORD"

	SERVER_PORT_DEFAULT               = 13332
	ORDER_MYSQL_DATABASE_NAME_DEFAULT = "order"
	ORDER_MYSQL_HOST_DEFAULT          = "localhost:33066"
	ORDER_MYSQL_USER_DEFAULT          = "root"
	ORDER_MYSQL_PASSWORD_DEFAULT      = "123456"
)
